import * as Phaser from "phaser";

export function create() {
  var shoebox = "Puma Shoes";
  var x = 10;
  var y = 0;
  var lineHeight = 10;
  var lines = Math.round(640 / lineHeight);

  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
  this.add.text(x, y, "In my box are " + shoebox);
  y = y + lineHeight;
}
